### import libraries

In [1]:
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F

### Testing various datatype

In [2]:
### testing various datatype
my_list =[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
print("Basic array: ", my_list)

Basic array:  [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


In [3]:
np1 = np.random.rand(3, 4)
print("Numpy array:", np1, np1.dtype)

Numpy array: [[0.36280278 0.5070583  0.4489824  0.5056577 ]
 [0.34900884 0.92324852 0.71276532 0.48388712]
 [0.88383555 0.35019864 0.17833346 0.69949763]] float64


In [4]:
tensor_2d = torch.randn(3,4)
print("tensor: ", tensor_2d)

tensor_3d = torch.zeros(2, 3, 4)
print("tensor 3d: ", tensor_3d)

tensor:  tensor([[-0.6585, -0.5928,  1.1420, -0.3452],
        [ 0.2774, -0.6232,  0.1826,  1.2637],
        [-2.1388,  1.3553,  0.1820, -0.8033]])
tensor 3d:  tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [5]:
my_tensor = torch.tensor(np1)
print("tensor from numpy array:", my_tensor)

tensor from numpy array: tensor([[0.3628, 0.5071, 0.4490, 0.5057],
        [0.3490, 0.9232, 0.7128, 0.4839],
        [0.8838, 0.3502, 0.1783, 0.6995]], dtype=torch.float64)


In [6]:
### testing torch.tensor reshape and slice
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
## Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [16]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [17]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
my_torch4 = my_torch3.view(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
# with reshape and view, they will update 
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_torch5[1] = 616
my_torch5

tensor([  0, 616,   2,   3,   4,   5,   6,   7,   8,   9])

In [21]:
### Slices
my_torch7 = my_torch5
my_torch7
# grab a specific item
my_torch7[7]

tensor(7)

In [23]:
# grab slice
my_torch8 = my_torch7.reshape(5, 2)
my_torch8

tensor([[  0, 616],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

In [24]:
my_torch8[:,1]

tensor([616,   3,   5,   7,   9])

In [25]:
# return column
my_torch8[:,1:]

tensor([[616],
        [  3],
        [  5],
        [  7],
        [  9]])

In [7]:
# Create a Model Class that inherits nn.Module
class Neural_Net(nn.Module):
    # Input Layer (4 features of flower) 
    # --> Hidden Layer1 (number of neurons) 
    # --> H2(n) 
    # --> output(3 classes of iris flowers)
    def __init__(self, in_features = 4, h1 = 8, h2 = 8, out_features = 3):
        super().__init__() # instantiate our nn.Module
        self.fc1 = nn.Linear(in_features, h1)
        self.fc2 = nn.Linear(h1, h2)
        self.out = nn.Linear(h2, out_features)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.out(x)

        return x
    

In [8]:
# Pick a manual seed for randomization
torch.manual_seed(41)

# Create an instance of model
model = Neural_Net()